# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install -y libgdal-dev
after_success:
  - Rscript -e "remotes::install_github('newyorkcitycouncil/councilsnapshots', ref = Sys.getenv('TRAVIS_COMMIT'))"
  - Rscript -e "councilsnapshots::deploy_shinyapps_io()"
