# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install -y libgdal-dev
install:
- R -e 'install.packages("devtools")'
- R -e 'devtools::install_deps(dep = T)'

script:
- R CMD build .
- R CMD check *tar.gz
- Rscript -e "remotes::install_github('newyorkcitycouncil/council_snapshots', ref = Sys.getenv('TRAVIS_COMMIT'))"
- Rscript -e "devtools::test()"

deploy:
  provider: script
  script: Rscript -e "councilsnapshots::deploy_shinyapps_io()"
  on:
    all_branches: true
