# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install -y libgdal-dev
  - Rscript -e "remotes::install_github('newyorkcitycouncil/council_snapshots', ref = Sys.getenv('TRAVIS_COMMIT'));councilsnapshots::run_snapshots(port = 6012)"
deploy:
  provider: script
  script: Rscript -e "remotes::install_github('newyorkcitycouncil/council_snapshots', ref = Sys.getenv('TRAVIS_COMMIT'));councilsnapshots::deploy_shinyapps_io()"
  on:
    all_branches: true
